title: TTIL
email: me@toshimaru.net
description: >
  TTIL = Toshimaru's Today I Learned.
  ブログに書くまでもない雑多な学びを雑に書き散らします。
twitter_username: toshimaru_e
github_username:  toshimaru
permalink: /:year-:month-:day
timezone: Asia/Tokyo
google_analytics: UA-35177276-5
twitter:
  username: toshimaru_e
  card: summary
plugins:
- jekyll-feed
feed:
  posts_limit: 50
lang: ja
# Use remote_theme instead.
# theme: jekyll-theme-classless-simple
remote_theme: toshimaru/jekyll-theme-classless-simple
classless-simple:
  syntax: monokai
header_pages:
- about.md
- categories.html
giscus:
  repo: toshimaru/til.toshimaru.net
  repo-id: MDEwOlJlcG9zaXRvcnkyNTgyODI2ODQ=
  category-id: DIC_kwDOD2UUvM4CO8JI
