title: TTIL
email: me@toshimaru.net
description: >-
  TTIL = Toshimaru's Today I Learned.
  ブログに書くまでもない雑多な学びを雑に書き散らします。
twitter_username: toshimaru_e
github_username:  toshimaru
permalink: /:year-:month-:day
timezone: Asia/Tokyo
google_analytics: UA-35177276-5
remote_theme: jekyll/minima
twitter:
  username: toshimaru_e
  card: summary
lang: ja
