title: TTIL
email: me@toshimaru.net
description: >-
  TTIL = Toshimaru's Today I Learned.
  ブログに書くまでもない雑多な学びを雑に書き散らします。
twitter_username: toshimaru_e
github_username:  toshimaru
permalink: /:year-:month-:day
timezone: Asia/Tokyo
google_analytics: UA-35177276-5
twitter:
  username: toshimaru_e
  card: summary
plugins:
  - jekyll-feed
lang: ja
# Use remote_theme instead.
# theme: jekyll-theme-classless-simple
remote_theme: toshimaru/jekyll-theme-classless-simple
classless-simple:
  syntax: monokai
header_pages:
- about.md
