name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Jekyll Build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Jekyll Build
      run: bundle exec jekyll build
    - name: GitHub Pages health check
      run: bundle exec github-pages health-check
